// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Hive.Infrastructure.Migrations;

[DbContext(typeof(Hive.Infrastructure.Persistence.HiveDbContext))]
[Migration("20260911173000_RemoveHiringTables")]
partial class RemoveHiringTables
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        // The current model snapshot supplies the post-removal model.
    }
}
