// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Hive.Infrastructure.Migrations;

[DbContext(typeof(Hive.Infrastructure.Persistence.HiveDbContext))]
[Migration("20260911170000_RemoveDocumentsTable")]
partial class RemoveDocumentsTable
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        // The migration's schema operation is defined in the companion migration file.
        // The current model snapshot supplies the post-removal model.
    }
}
